<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="821" started-at="2016-02-01T07:41:49Z" finished-at="2016-02-01T07:41:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="821" started-at="2016-02-01T07:41:49Z" finished-at="2016-02-01T07:41:50Z">
      <class name="TestCases.TestCases_1">
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:TestCases.TestCases_1@7504d7f2]" name="setUp" is-config="true" duration-ms="31250" started-at="2016-02-01T13:11:18Z" finished-at="2016-02-01T13:11:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@3b9649c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="startup()[pri:0, instance:TestCases.TestCases_1@7504d7f2]" name="startup" duration-ms="802" started-at="2016-02-01T13:11:49Z" finished-at="2016-02-01T13:11:50Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at TestCases_Actions.LoginActions.startup(LoginActions.java:29)
	at TestCases.TestCases_1.startup(TestCases_1.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestCases_1@7504d7f2]" name="tearDown" is-config="true" duration-ms="33" started-at="2016-02-01T13:11:50Z" finished-at="2016-02-01T13:11:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestCases_1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
